spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:ptstudio}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER:ptstudio}
    password: ${DB_PASSWORD:ptstudio}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

ptstudio:
  messaging:
    reservation:
      topic: ${PT_RESERVATION_EVENT_TOPIC:ptstudio.reservation.changed}
      created-tag: ${PT_RESERVATION_CREATED_TAG:reservation_created}
      canceled-tag: ${PT_RESERVATION_CANCELED_TAG:reservation_canceled}
