spring:
  application:
    name: ptstudio-biz-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8718}
        port: ${SENTINEL_TRANSPORT_PORT:8721}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
